POST https://findit-08qb.onrender.com/user/create
Content-type: application/json

{
    "user": "felipe",
    "senha": 1234,
    "cargo_id": 1,
    "imgUserPhoto": ""
    
}

###

PUT http://localhost:3000/usuarios/pendentes/:1