POST https://findit-08qb.onrender.com/user/create
Content-type: application/json

{
    "user": "felipe",
    "senha": 1234,
    "cargo_id": 1,
    "imgUserPhoto": ""
    
}

###

DELETE  http://localhost:3000/excluir-imagem
Content-type: multipart/form-data

{
    imagemUrl: "https://res.cloudinary.com/dl8dwltol/image/upload/v1742264516/uploads/img_1742264476235.jpg";
}

###

POST https://findit-08qb.onrender.com/user/login
Content-type: application/json

{
    "user": "felipe",
    "password": 2007,   
}